sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "c0M6FnVYDJOfq1XFerFmhQO4E+MtuwqQkptWIJf1O6q+tmBgeDj0NFNFkVB3meT7mbSbtppL2i8ZnEi2lJIUaSqqf5LXXfD/Nlss+aZLPhDUa8SM+nBKXPlQC7aHI+78hN3+yCiYzyw9c1ZLtfksf0QygSW9FrAXq5oyQzzf4XLYGXQbcvTvc7beqonwUiykeCVdhOHpU2jdnCnulE+sfSwCjzGhI0xDRfyFo9dr+sYqn1yavbWYJznclcjCdQtR2H4vyL0P9DGnNmnlnwYBwPFC/G1CA9SUfOMeNWB6Hbxgb6bBTmU172PtDqHa3dGF/F9YGsy7CHwf0LlIPvGwdyoA3MwvCpex9ehgiNuFMmCua7d68RSx8mlHmAGdA4QopckwqUsvSLB5SPX3Ot/FmuDpMF8aLNAsJ8STCQMDWQZwc1QDdI2+Dqmxleq4SOnmo7ThnzV01uGgfVZPmVu5cp6Hi/7cvSVVOFG29kZq4tjbOzWf8T7ySlQInTCGvNoG3pKiIWfdTM1xw1pq2/CJkwq0vUfCGjwN5Yz1R73x0LBRCrErU5Jml73j4SDLrLJskhGFNRp/GmRzZ4QlUwDl4761diPKgIpWRF/f3rxkIhk/eASfHA0sluKp7V9xIe4k0RtKbU0p57R6s98Pqm7yyVWT4YY5SPtBh6d6GEyJM/M="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
